### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Schaefer-B** [Schaefer-B/ECMC#2]
- [x] add exclamation points to two functions
- [x] check_tuning_convergence!: rename variance to standard_deviation
- [x] check_tuning_convergence!: delete "algorithm" from arguments and put ecmc_tuner_state as first argument (?)
- [x] ecmc_ECMCstate.jl: default values for all the zeros
- [x] ecmc_ECMCstate.jl: change step_variance to be set on 0.1*tuned_delta
- [x] ecmc_ECMCstate.jl: write documentation string for everything
- [ ] ecmc_sampler.jl: write documentation string for everything
- [x] write adapt_delta with package Optim
- [x] change acc_C array to only hold number of accepts
- [x] call _change_direction and evaluate MH acceptance in seperate function
- [ ] show every progress bar for every thread if possible
- [x] implement calling of different step variance options (normal, uniform, user-defined, etc)
- [x] rewrite NaiveAdaption to add and use approximations for gradients and more
- [x] change ECMCTunerState so adaption parameters can be optimized by Optim
- [x] add GoogleAdaption
- [x] change ECMCTunerState to hold GoogleAdaption parameters
- [x] change convergence criteria to current acceptance ratio
- [x] change additional convergence criteria for std
- [x] add convergence criteria for minimum steps to assure a more meaningful delta is reached (if maybe starting area of first sample was bad)
- [x] add break in tuning if max tuning steps are reached
- [x] add burnin for sampling
- [x] add alpha adaption for google tuning so its more stable
- [x] change state so that the current energy is saved and doesn't need to be reevaluated every step
- [ ]
